openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/tasks:
    get:
      summary: ''
      operationId: getApiTasks
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 4
                      title: test2
                      description: test
                      completed: true
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 5
                      title: Dr.
                      description: 'Temporibus qui alias tempora qui nostrum aspernatur illum. Amet nemo ea similique error quis.'
                      completed: false
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 6
                      title: Mrs.
                      description: 'Perferendis magnam nam fuga assumenda officiis tempore. Rerum quia id culpa quia. Consequatur praesentium quo quia iusto animi. Veritatis necessitatibus atque aliquid sunt ipsam accusamus.'
                      completed: false
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 7
                      title: Mr.
                      description: 'Voluptatum ab eligendi corporis cum porro et et. Non sed illo voluptas non. Itaque voluptatem aut est dicta soluta dolor. Accusantium qui corporis at nobis. Tempora quae nisi ab totam quae eligendi.'
                      completed: false
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 8
                      title: test2
                      description: test
                      completed: true
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 9
                      title: test2
                      description: test
                      completed: true
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 10
                      title: Mr.
                      description: 'Nobis qui veniam nulla similique harum. Nostrum enim dolor consectetur mollitia voluptates voluptas ab.'
                      completed: false
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 11
                      title: Mr.
                      description: 'Sint ducimus sit dolorum itaque asperiores. Ut quia excepturi vero. Quis fuga id odit qui.'
                      completed: false
                      user:
                        id: 2
                        name: Teee
                    -
                      id: 12
                      title: Mr.
                      description: 'Ad et natus temporibus aperiam sunt. Odio asperiores tempore quibusdam ex est molestiae sunt. Nihil impedit perferendis recusandae non laboriosam eos. Rerum ratione aut quia.'
                      completed: false
                      user:
                        id: 2
                        name: Teee
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 4
                        title: test2
                        description: test
                        completed: true
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 5
                        title: Dr.
                        description: 'Temporibus qui alias tempora qui nostrum aspernatur illum. Amet nemo ea similique error quis.'
                        completed: false
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 6
                        title: Mrs.
                        description: 'Perferendis magnam nam fuga assumenda officiis tempore. Rerum quia id culpa quia. Consequatur praesentium quo quia iusto animi. Veritatis necessitatibus atque aliquid sunt ipsam accusamus.'
                        completed: false
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 7
                        title: Mr.
                        description: 'Voluptatum ab eligendi corporis cum porro et et. Non sed illo voluptas non. Itaque voluptatem aut est dicta soluta dolor. Accusantium qui corporis at nobis. Tempora quae nisi ab totam quae eligendi.'
                        completed: false
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 8
                        title: test2
                        description: test
                        completed: true
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 9
                        title: test2
                        description: test
                        completed: true
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 10
                        title: Mr.
                        description: 'Nobis qui veniam nulla similique harum. Nostrum enim dolor consectetur mollitia voluptates voluptas ab.'
                        completed: false
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 11
                        title: Mr.
                        description: 'Sint ducimus sit dolorum itaque asperiores. Ut quia excepturi vero. Quis fuga id odit qui.'
                        completed: false
                        user:
                          id: 2
                          name: Teee
                      -
                        id: 12
                        title: Mr.
                        description: 'Ad et natus temporibus aperiam sunt. Odio asperiores tempore quibusdam ex est molestiae sunt. Nihil impedit perferendis recusandae non laboriosam eos. Rerum ratione aut quia.'
                        completed: false
                        user:
                          id: 2
                          name: Teee
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 4
                        title:
                          type: string
                          example: test2
                        description:
                          type: string
                          example: test
                        completed:
                          type: boolean
                          example: true
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 2
                            name:
                              type: string
                              example: Teee
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiTasks
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kkhazckawpleiljtx
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Illo eaque voluptatem tenetur optio.'
                  nullable: false
                completed:
                  type: boolean
                  description: ''
                  example: true
                  nullable: true
              required:
                - title
                - description
      security: []
  '/api/tasks/{id}':
    get:
      summary: ''
      operationId: getApiTasksId
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'This field is required when none of <code>description</code> and <code>completed</code> are present. Must not be greater than 255 characters.'
                  example: oijxv
                  nullable: true
                description:
                  type: string
                  description: 'This field is required when none of <code>title</code> and <code>completed</code> are present.'
                  example: 'Quis illum pariatur ut.'
                  nullable: true
                completed:
                  type: boolean
                  description: 'This field is required when none of <code>title</code> and <code>description</code> are present.'
                  example: true
                  nullable: true
      security: []
    delete:
      summary: ''
      operationId: deleteApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: dolorem
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
